git-name: Go SemVer Release
git-email: go-semver@release.ci

tag-prefix: v

branches:
  - name: main
  - name: rc
    prerelease: true

rules:
  minor:
    - feat
  patch:
    - fix
    - perf
    - revert