name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      # Insert your build process and unit tests here
      # ...

  versioning:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.go-semver.outputs.NEW_RELEASE }}
      semver: ${{ steps.go-semver.outputs.SEMVER }}
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0 # Fetches tags

      # Install Go Semver Release
      - name: Install Go Semver Release
        run: |
          curl -SL https://github.com/s0ders/go-semver-release/releases/latest/download/go-semver-release-linux-amd64 -o ./go-semver-release \
          && chmod +x ./go-semver-release

      # Running in dry-run mode since the repository remote will not be tagged since the program is running
      # are in local mode.
      - name: Go Semver Release
        id: go-semver
        run: ./go-semver-release release . --config .semver.yaml --dry-run

      # Configuring Git username and email that will appear as the tag author
      - name: Git Configuration
        run: |
          git config --global user.email "go-semver-release@ci.com"
          git config --global user.name "Go Semver Release"

      # Actually pushing SemVer tag to remote
      - name: Push Tag
        run: |
          git tag --annotate ${{ steps.go-semver.outputs.SEMVER }} --message "${{ steps.go-semver.outputs.SEMVER }}"
          git push origin ${{ steps.go-semver.outputs.SEMVER }}

  release:
    runs-on: ubuntu-latest
    needs: build
    # Only run this job if a new release was detected
    if: ${{needs.go-build.outputs.release == 'true'}}
    env:
      RELEASE_TAG: ${{needs.build.outputs.semver}}
    steps:
      - uses: actions/checkout@v4.1.4

      # Insert your release process here
      # ...