name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      # Insert your build process and tests here
      # ...

  versioning:
    runs-on: ubuntu-latest
    needs: build-and-test
    outputs:
      release: ${{ steps.go-semver.outputs.NEW_RELEASE }}
      semver: ${{ steps.go-semver.outputs.SEMVER }}
    steps:
      - uses: actions/checkout@v4.1.4

      # Install Go Semver Release
      - name: Install Go Semver Release
        run: |
          curl -SL https://github.com/s0ders/go-semver-release/releases/latest/download/go-semver-release-linux-amd64 -o ./go-semver-release \
          && chmod +x ./go-semver-release

      # Tests are good, versioning the repository (if any new release is found)
      - name: Go Semver Release
        id: go-semver
        env:
          GO_SEMVER_RELEASE_ACCESS_TOKEN: ${{ secrets.accessToken }}
        run: ./go-semver-release release https://github.com/my/repo.git --config .semver.yaml

  release:
    runs-on: ubuntu-latest
    needs: versioning
    # Only run this job if a new release was detected
    if: ${{needs.versioning.outputs.release == 'true'}}
    env:
      RELEASE_TAG: ${{needs.build.outputs.semver}}
    steps:
      - uses: actions/checkout@v4.1.4

      # Insert your release process here
      # ...
