version: 1

env:
  - CGO_ENABLED=0

goos: darwin
goarch: arm64

main: ./main.go

binary: go-semver-release-{{ .Os }}-{{ .Arch }}

ldflags:
  - "-X github.com/s0ders/go-semver-release/v4/cmd.version={{ .Env.VERSION }}"
  - "-X github.com/s0ders/go-semver-release/v4/cmd.buildNumber={{ .Env.BUILD_NUMBER }}"
  - "-X github.com/s0ders/go-semver-release/v4/cmd.commitHash={{ .Env.COMMIT_HASH }}"