version: 1

env:
  - CGO_ENABLED=0

goos: linux
goarch: arm64

main: ./main.go

binary: go-semver-release-{{ .Os }}-{{ .Arch }}

ldflags:
  - "-X github.com/s0ders/go-semver-release/v5/cmd.cmdVersion={{ .Env.VERSION }}"
  - "-X github.com/s0ders/go-semver-release/v5/cmd.buildNumber={{ .Env.BUILD_NUMBER }}"
  - "-X github.com/s0ders/go-semver-release/v5/cmd.buildCommitHash={{ .Env.COMMIT_HASH }}"
  - "-w"
  - "-s"
